{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cyberchef.serviceAccountName" . }}
  namespace: {{ include "cyberchef.namespace" . }}
  labels:
    {{- include "cyberchef.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "cyberchef.serviceAccountName" . }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl (toYaml .Values.commonAnnotations) . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
