{{- if .Values.ingress.enabled }}
{{- $fullName := include "dillinger.fullname" . }}
{{- $svcPort := .Values.service.port }}
{{- $svcPortName := include "dillinger.portName" . }}
---
apiVersion: {{ include "dillinger.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "dillinger.fullname" . }}
  namespace: {{ include "dillinger.namespace" . }}
  labels:
    {{- include "dillinger.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "dillinger.fullname" . }}
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- tpl (toYaml .Values.commonAnnotations) . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- tpl (toYaml .Values.ingress.annotations) . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $svcPortName }}
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
      {{- if ne .Values.ingress.hostname "*" }}
      host: {{ .Values.ingress.hostname }}
      {{- end}}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
    {{- if .Values.ingress.extraRules }}
    {{- tpl (toYaml .Values.ingress.extraRules) . | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" (include "dillinger.fullname" .) }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- tpl (toYaml .Values.ingress.extraTls) . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
