{{- if .Values.ingress.secrets }}
{{- range $index, $secret := .Values.ingress.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ include "dillinger.namespace" $ }}
  labels:
    {{- include "dillinger.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ include "dillinger.fullname" $ }}-tls-secret
    {{- if $.Values.commonLabels }}
    {{- tpl (toYaml $.Values.commonLabels) $ | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- tpl (toYaml $.Values.commonAnnotations) $ | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $secret.certificate | b64enc }}
  tls.key: {{ $secret.key | b64enc }}
{{- end }}
{{- end }}
