---
# --------------------------------------------------------------------------- #
# General                                                                     #
# --------------------------------------------------------------------------- #

name: Validate Helm Docs

on:
  push:
    branches: ["**"]

# --------------------------------------------------------------------------- #
# Job Configuration                                                           #
# --------------------------------------------------------------------------- #

jobs:
  verify-helm-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Set up Helm
        uses: azure/setup-helm@v4 # https://github.com/azure/setup-helm
        with:
          version: v3.14.4

      - name: Install helm-docs
        uses: gabe565/setup-helm-docs-action@v1 # https://github.com/gabe565/setup-helm-docs-action

      - name: Generate Helm docs
        run: helm-docs

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Detected uncommitted README changes. Please commit or revert them."
            echo "Hint: You can run 'helm-docs' locally or use pre-commit to auto-generate updated READMEs."
            exit 1
          fi
